# Third-party integration test.

cc_test(
    name = "third_party_test",
    srcs = ["third_party_test.cc"],
    deps = [
        "@boost//:filesystem",
        "@com_github_pocoproject_poco//:PocoFoundation",
        "@com_google_googletest//:gtest_main",
        "@com_google_protobuf//:protobuf",
    ],
)
