# Third-party integration test.

cc_test(
    name = "third_party_test",
    srcs = ["third_party_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@com_google_protobuf//:protobuf",
        "//conda:boost_filesystem",
    ],
)
